### ISSUE TITLE
I can't set it up

### ISSUE THREAD

**Issue by 1337LV** [minthemiddle/todoist-scheduler#6]
Forst of all, I was searching for this feature for days and finally found this but I can't set it up because I'm not familiar with Python.

I downloaded the latest Python from web
Installed it
Opened README.md file with Notepad++
here

- (Bash) `EXPORT TODOIST_KEY = 'your_key_here'` (or add to `.zshrc` or the like)

your_key_here replaced with my API key

saved file
Launched todoist python file

it pops up and closes straight after in 1 sec.

Can you help me, please?

**Comment by minthemiddle** [comment]
First off, sorry that you need to use Python to use this tool right now. I might re-write the tool in Javascript that can just be run from the browser.

For your current problem:
- I assume that you are using Windows
- Make sure you installed Python as described [here](https://realpython.com/installing-python/#windows)
- If you forgot the checkbox "Add to path", please reinstall
- After
Can you please open a terminal as described [here](https://www.computerhope.com/issues/chusedos.htm)
- Navigate to the folder that has the `todoist-scheduler`
- What output does `python3 todoist.py` give you then?

**Comment by 1337LV** [comment]
Good evening, thank you for your fast reply.
I realized the first problem I tried to launch the file trough python terminal, not trough cmd.

Her's error:

```
C:\todoist-scheduler-master>py todoist.py
Traceback (most recent call last):
  File "todoist.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

C:\todoist-scheduler-master>
```

**Comment by 1337LV** [comment]
Fixed previous error with this:

C:\mypath...\Python37\Scripts\easy_install.exe requests

Then I had this error:
```
C:\todoist-scheduler-master>py todoist.py
Traceback (most recent call last):
  File "todoist.py", line 4, in <module>
    your_token = os.environ['TODOIST_KEY']
  File "C:\mypath...\Python37\lib\os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'TODOIST_KEY'
```

After as a solution I've tried to paste API token from todoist settings (integrations) into both files:

README.md
todoist.py

and the next error is:

```
C:\todoist-scheduler-master>py todoist.py
Traceback (most recent call last):
  File "todoist.py", line 4, in <module>
    your_token = os.environ['mykeyishidden']
  File "C:\mypath...\Python37\lib\os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'mykeyishidden'

C:\todoist-scheduler-master>
```

**Comment by 1337LV** [comment]
And the last thing I did was:

Control Panel\System and Security\System
Advanced system settings
Advanced
Environment Variables
System Variables
NEW

Variable: TODOIST_KEY
Variable value: API token integrations

Whola! :)

**Comment by minthemiddle** [comment]
So it works now? Because the last error message (`KeyError: '…'`) does mean that you did not set your API key as an Environment variable.

Actually, you could also just hardcode (= copy) your API key to the `todoist.py` file.

So the new code would be:
`your_token = 'TheTodoistAPIKey'`

Make sure though that you do not publish your API key by committing your changed `todoist.py` to Github. As long as you just use it locally, you are fine to go.

You don't need to change the API key in the `readme.md`, this is just the description and does have no effect on the script itself.

**Comment by 1337LV** [comment]
Now everything works, thank you very much. I tried hardcode copy to todoist.py file but it didn't work.

I'm not a coder but I will try to change label names from m30 to 30m and add few more time m10, m60, m120 and m180 hopefully I will figure out how to do it.

**Comment by 1337LV** [comment]
Very good it works perfectly now 👍 

I changed label names and added additional times as well, now I have 10-time labels:

5min
10min
15min
25min
30min
45min
60min
120min
180min
240min

Looking forward to the web version, this could be very useful for others as well!
