### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by 1337LV** [minthemiddle/todoist-scheduler#8]
Hi,

I was successfully using this scheduler but while ago it stopped working and I can't figure out where is the problem. Maybe someone can help me. From basic code, I even added there more task lengths and it worked well but now shows me this error:

```
<Response [410]>
Traceback (most recent call last):
  File "C:\....\todoist.py", line 68, in <module>
    print("Task Count: {}".format(count_tasks(m5,m10,m25,m45,m60,m90,m120,m180,m240,m240)))
  File "C:\....\todoist.py", line 21, in count_tasks
    return len(i5)+len(i10)+len(i45)+len(i60)+len(i90)+len(i120)+len(i180)+len(i240)+len(i300)
TypeError: object of type 'Response' has no len()
```

**Comment by minthemiddle** [comment]
I will look into this very soon, but don't have Windows. So if someone with Windows reads this, please try it out and give feedback, please.

**Comment by 1337LV** [comment]
Thank you, looking forward to your answer.

**Comment by 1337LV** [comment]
Is there any chance of fixing this in the near future?

**Comment by minthemiddle** [comment]
The API URL had changed. I updated it. Can you please try it again, @1337LV?
Just go to your directory and use `git pull` to get the latest version.

**Comment by 1337LV** [comment]
@minthemiddle thank you very much it works now!

**Comment by 1337LV** [comment]
By the way, I have updated code to more time labels, maybe you can share it as well if someone wants to use it with expanded time filters.

[https://files.fm/u/rany9g9v](https://files.fm/u/rany9g9v)
